[build]
  base = "quick-cart"
  command = "npm run build"
  publish = "quick-cart/.next" 

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
