[build]
  base = "quick-cart"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# API Proxy to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://gocart-backend-oakq.onrender.com/:splat"
  status = 200
  force = true
