[build]
  base = "quick-cart"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Proxy API requests to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://gocart-backend-oakq.onrender.com/api/:splat"
  status = 200
  force = true
